name: Testing

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  DEFAULT_PYTHON: "3.11"

jobs:
  pytest:
    name: Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #python: ["3.11", "3.12"]
        python: ["3.6", "3.8", "3.9"]
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4.1.7
      - name: 🏗 Set up Poetry
        run: pipx install poetry
      - name: 🏗 Set up Python ${{ matrix.python }}
        id: python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: ${{ matrix.python }}
          cache: "poetry"
      - name: 🏗 Install workflow dependencies
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
      - name: 🏗 Install dependencies
        run: poetry install --no-interaction
      - name: 🚀 Run pytest
        run: poetry run pytest --cov src tests
      - name: ⬆️ Upload coverage artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: coverage-${{ matrix.python }}
          path: .coverage
